// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 25/6/2026, 10:16:33 p. m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ACER/Documents/yo/memora/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ACER/Documents/yo/memora/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ACER/Documents/yo/memora/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ACER/Documents/yo/memora/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ACER/Documents/yo/memora/plugins/**/*.{js,ts,mjs}","C:/Users/ACER/Documents/yo/memora/composables/**/*.{js,ts,mjs}","C:/Users/ACER/Documents/yo/memora/utils/**/*.{js,ts,mjs}","C:/Users/ACER/Documents/yo/memora/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ACER/Documents/yo/memora/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ACER/Documents/yo/memora/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ACER/Documents/yo/memora/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;